services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
      - "443:443"
    volumes:
      - /home/abrahamchalita/zentinel-project/zentinel-consulting/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/zentinel.mx/fullchain.pem:/etc/letsencrypt/live/zentinel.mx/fullchain.pem
      - /etc/letsencrypt/live/zentinel.mx/privkey.pem:/etc/letsencrypt/live/zentinel.mx/privkey.pem
    depends_on:
      - web

volumes:
  pgdata:
